# Configuration defaults

# Experiment settings
task: classification         # 'classification', 'segmentation', etc.
mode: train                  # 'train', 'test', or 'predict'
seed: 42                     # Random seed for reproducibility

# Data settings
data_name: domars16k         # Name of the dataset
dataset_path: /data/hkerner/MarsBench/NewDatasets  # Base path to datasets
few_shot: null               # Support [null, 1, 2, 5, 10, 15, 20]
partition: null              # Supported: [null, 0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1]
test_after_training: true    # Run test after training completes

# Model settings
model_name: resnet101        # Name of the model architecture
training_type: feature_extraction  # 'scratch_training', 'feature_extraction', 'transfer_learning'
checkpoint_path: null        # Path to a .ckpt file to resume training

# Output settings
output_path: outputs         # Directory for outputs (models, logs, metrics)
prediction_output_path: null # Directory for prediction outputs; defaults to output_path/predictions

defaults:
  - _self_
  - transforms: default
  - data: classification/domars16k  # task/data_name updated using load_dynamic_configs
  - prompts: classification/domars16k  # Optional for VLM zero-shot
  - model: classification/resnet101  # task/model_name updated using load_dynamic_configs
  - vlm: gemini
  - training: ${oc.env:HYDRA_TRAINING,dev}  # Use test config in test environment
  - test: default
  - logger: default
  - callbacks: default

data:
  split:
    train: 0.6
    val: 0.2
    test: 0.2
  valid_image_extensions:
    - jpg
    - JPG
    - jpeg
    - JPEG
    - png
    - PNG
    - tif
    - TIF

hydra:
  job:
    chdir: True
  run:
    dir: ${output_path}/${task}/${data_name}/${model_name}/${now:%Y-%m-%d_%H-%M-%S}
