name: gemini
model_name: "gemini-2.0-flash" # Or your preferred vision model
temperature: 0.4
max_batches: 2  # set null to process all batches
safety_settings:
  - category: HARM_CATEGORY_HARASSMENT
    threshold: BLOCK_NONE
  - category: HARM_CATEGORY_HATE_SPEECH
    threshold: BLOCK_NONE
  - category: HARM_CATEGORY_SEXUALLY_EXPLICIT
    threshold: BLOCK_NONE
  - category: HARM_CATEGORY_DANGEROUS_CONTENT
    threshold: BLOCK_NONE
