repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        exclude: ^(legacy_code)
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        language_version: python3.11
        exclude: ^(legacy_code)
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        exclude: ^(legacy_code)
-   repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
        exclude: ^(data|examples|legacy_code)
        additional_dependencies: ['flake8-pyproject']
# -   repo: local
#     hooks:
#     -   id: pytest-check
#         name: pytest-check
#         entry: env HYDRA_TRAINING=test pytest
#         language: system
#         pass_filenames: false
#         always_run: true
