# Early Stopping
early_stopping:
  _target_: pytorch_lightning.callbacks.early_stopping.EarlyStopping
  monitor: 'val_loss'
  patience: 5
  mode: 'min'

# Best Model Checkpoint
best_checkpoint:
  _target_: pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint
  monitor: 'val_loss'
  save_top_k: 1
  mode: 'min'
  filename: 'best-{epoch:02d}-{val_loss:.4f}'
  save_last: false

# Last Model Checkpoint
last_checkpoint:
  _target_: pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint
  save_top_k: 0
  save_last: true
  filename: 'last'
