defaults:
  - _self_
  - data: domars16k
  - model: fasterrcnn
  - transforms: default
  - training: dev
  - optimizer: adam
  - criterion: cross_entropy
  - test: default

seed: 42

# Use data.task if defined, otherwise default to classification
task: ${oc.decode:${oc.select:data.task,classification}}

data:
  split:
    train: 0.6
    val: 0.2
    test: 0.2
  valid_image_extensions:
    - jpg
    - JPG
    - jpeg
    - JPEG
    - png
    - PNG
    - tif
    - TIF

hydra:
  job:
    chdir: True
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
