# Configuration defaults
task: classification
mode: train  # train, test, or predict
data_name: domars16k
model_name: resnet18
dataset_path: /data/hkerner/MarsBench/Datasets
new_dataset_path: /data/hkerner/MarsBench/NewDatasets
output_path: outputs
seed: 42
test_after_training: false  # Whether to run test after training is complete
prediction_output_path: null  # Custom path for prediction outputs, if null uses output_path/predictions

# Model loading options
checkpoint_path: null  # Path to model checkpoint file (.ckpt)

defaults:
  - _self_
  - transforms: default
  - data: classification/domars16k  # task/data_name updated using load_dynamic_configs
  - model: classification/resnet18  # task/model_name updated using load_dynamic_configs
  - training: ${oc.env:HYDRA_TRAINING,dev}  # Use test config in test environment
  - test: default
  - logger: default
  - callbacks: default

data:
  split:
    train: 0.6
    val: 0.2
    test: 0.2
  valid_image_extensions:
    - jpg
    - JPG
    - jpeg
    - JPEG
    - png
    - PNG
    - tif
    - TIF

hydra:
  job:
    chdir: True
  run:
    dir: ${output_path}/${task}/${data_name}/${model_name}/${now:%Y-%m-%d_%H-%M-%S}
