# Configuration defaults
task: classification
mode: train  # train, test, or predict
data_name: domars16k
model_name: resnet18
dataset_path: /data/hkerner/MarsBench/Datasets
output_path: outputs
seed: 42

defaults:
  - _self_
  - transforms: default
  - data: ${oc.select:task, classification}/${oc.select:data_name, domars16k}
  - model: ${oc.select:task, classification}/${oc.select:model_name, resnet18}
  - training: dev
  - optimizer: adam
  - criterion: cross_entropy
  - callbacks: default
  - test: default
  - logger: default

data:
  split:
    train: 0.6
    val: 0.2
    test: 0.2
  valid_image_extensions:
    - jpg
    - JPG
    - jpeg
    - JPEG
    - png
    - PNG
    - tif
    - TIF

hydra:
  job:
    chdir: True
  run:
    dir: ${output_path}/${task}/${data_name}/${model_name}/${now:%Y-%m-%d_%H-%M-%S}
